packages:
  - "packages/*"

catalog:
  # Core LiveStore dependencies
  "@livestore/livestore": "latest"
  "@livestore/adapter-web": "latest"
  "@livestore/adapter-node": "latest"
  "@livestore/react": "latest"
  "@livestore/sync-cf": "latest"
  "@livestore/utils": "latest"
  "@livestore/common": "latest"
  "@livestore/devtools-vite": "latest"
  "@livestore/wa-sqlite": "1.0.5-dev.2"
  "@livestore/webmesh": "latest"

  # Effect ecosystem (for LiveStore)
  "effect": "3.15.5"
  "@effect/platform": "0.82.8"
  "@effect/platform-node": "0.73.4"
  "@effect/platform-node-shared": "0.35.5"
  "@effect/cluster": "0.34.5"
  "@effect/experimental": "0.48.3"
  "@effect/typeclass": "0.29.0"
  "@effect/schema": "0.73.4"
  "@effect/cli": "0.61.8"
  "@effect/opentelemetry": "0.48.8"
  "@effect/sql": "0.21.4"
  "@effect/rpc": "0.42.5"
  "@effect/vitest": "0.15.2"

  # React ecosystem
  "react": "19.0.0"
  "react-dom": "19.0.0"
  "@types/react": "^19.1.2"
  "@types/react-dom": "^19.0.4"

  # UI components (shadcn/ui + Radix)
  "@radix-ui/react-dropdown-menu": "^2.1.15"
  "@radix-ui/react-separator": "^1.1.7"
  "@radix-ui/react-slot": "^1.2.3"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "lucide-react": "^0.513.0"
  "tailwind-merge": "^3.3.0"

  # Styling & CSS
  "tailwindcss": "^4.1.8"
  "@tailwindcss/cli": "^4.1.8"
  "@tailwindcss/postcss": "^4.1.8"
  "autoprefixer": "^10.4.21"
  "postcss": "^8.5.4"
  "tw-animate-css": "^1.3.4"

  # Build tools & bundling
  "vite": "^6.3.4"
  "@vitejs/plugin-react": "^4.3.4"
  "typescript": "^5.8.3"
  "@types/node": "^22.15.30"

  # Python execution
  "pyodide": "^0.27.7"

  # Development & utilities
  "wrangler": "^4.14.4"
  "concurrently": "^9.1.2"

  # Additional utilities from original project
  "@overengineering/fps-meter": "0.1.2"
